version: 2.1

jobs:
  build:
    docker:
      - image: << parameters.ruby_version >>
      - image: postgres:11.19-alpine
        environment:
          POSTGRES_HOST_AUTH_METHOD: "trust"
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    parameters:
      ruby_version:
        type: string
      gemfile:
        type: string
    environment:
      BUNDLE_GEMFILE: << parameters.gemfile >>
    steps:
      - checkout
      # Restore Cached Dependencies
      # - restore_cache:
      #     keys:
      #       - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.gemfile >>.lock" }}
      #       - gem-cache-v1-{{ arch }}-{{ .Branch }}
      #       - gem-cache-v1

      - run: bundle install --path vendor/bundle

      # - save_cache:
      #     key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.gemfile >>.lock" }}
      #     paths:
      #       - vendor/bundle

      - run:
          name: Update apt
          command: apt update -y

      - run:
          name: Install dependencies
          command: apt install -y curl postgresql-client default-mysql-client

      - run:
          name: Install dockerize
          command: curl -sfL $(curl -s https://api.github.com/repos/powerman/dockerize/releases/latest | grep -i /dockerize-$(uname -s)-$(uname -m)\" | cut -d\" -f4) | install /dev/stdin /usr/local/bin/dockerize

      - run:
          name: Configure config database.yml
          command: bundle exec rake db:copy_credentials

      - run:
          name: wait for postgresql
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: wait for mysql
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:test:prepare

      - run:
          name: Run tests
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/test-results/rspec/rspec.xml

      - store_test_results:
          path: ~/test-results/rspec/

workflows:
  tests:
    jobs:
      - build:
          matrix:
            parameters:
              ruby_version: ["ruby:2.7-buster", "ruby:3.0-buster", "ruby:3.1-buster", "ruby:3.2-buster"]
              gemfile: ["gemfiles/rails_5_2.gemfile", "gemfiles/rails_6_0.gemfile", "gemfiles/rails_6_1.gemfile", "gemfiles/rails_7_0.gemfile"]
            exclude:
              - ruby_version: "ruby:3.0-buster"
                gemfile: "gemfiles/rails_5_2.gemfile"
              - ruby_version: "ruby:3.1-buster"
                gemfile: "gemfiles/rails_5_2.gemfile"
              - ruby_version: "ruby:3.2-buster"
                gemfile: "gemfiles/rails_5_2.gemfile"
