name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        id: commit_files
        env:
          ACTION_EMAIL: action@github.com
          ACTION_USERNAME: GitHub Action
        run: |
          git config --local user.email "$ACTION_EMAIL"
          git config --local user.name "$ACTION_USERNAME"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_OUTPUT || echo "No changes to CHANGELOG.md" && echo "push=false" >> $GITHUB_OUTPUT
      - run: |
          echo ${{ steps.commit_files.outputs.push}}
      - name: Push changes to master
        if: ${{ steps.commit_files.outputs.push == 'true' }}
        env:
          # CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
          CI_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        run: |
          git push "https://$GITHUB_ACTOR:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master

      - name: Cherry-pick changelog to development
        if: ${{ steps.commit_files.outputs.push == 'true' }}
        env:
          ACTION_EMAIL: action@github.com
          ACTION_USERNAME: GitHub Action
        run: |
          git config --local user.email "$ACTION_EMAIL"
          git config --local user.name "$ACTION_USERNAME"
          commit_hash=`git show HEAD | egrep commit\ .+$ | cut -d' ' -f2`
          git checkout development
          git pull
          git cherry-pick $commit_hash
          git push
